/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type ContentImage = {
	_type: 'contentImage';
	asset?: {
		_ref: string;
		_type: 'reference';
		_weak?: boolean;
		[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
	};
	media?: unknown;
	hotspot?: SanityImageHotspot;
	crop?: SanityImageCrop;
	alt?: string;
	caption?: string;
};

export type SanityImageCrop = {
	_type: 'sanity.imageCrop';
	top?: number;
	bottom?: number;
	left?: number;
	right?: number;
};

export type SanityImageHotspot = {
	_type: 'sanity.imageHotspot';
	x?: number;
	y?: number;
	height?: number;
	width?: number;
};

export type BlockContent = Array<
	| {
			children?: Array<{
				marks?: Array<string>;
				text?: string;
				_type: 'span';
				_key: string;
			}>;
			style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote';
			listItem?: 'bullet' | 'number';
			markDefs?: Array<{
				href?: string;
				blank?: boolean;
				_type: 'link';
				_key: string;
			}>;
			level?: number;
			_type: 'block';
			_key: string;
	  }
	| {
			asset?: {
				_ref: string;
				_type: 'reference';
				_weak?: boolean;
				[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
			};
			media?: unknown;
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			alt?: string;
			caption?: string;
			_type: 'image';
			_key: string;
	  }
>;

export type PageContent = {
	_id: string;
	_type: 'pageContent';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	newsletter?: {
		contentImage?: {
			asset?: {
				_ref: string;
				_type: 'reference';
				_weak?: boolean;
				[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
			};
			media?: unknown;
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			alt?: string;
			caption?: string;
			_type: 'image';
		};
		title?: string;
		body?: BlockContent;
	};
	region?: {
		contentImage?: {
			asset?: {
				_ref: string;
				_type: 'reference';
				_weak?: boolean;
				[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
			};
			media?: unknown;
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			alt?: string;
			caption?: string;
			_type: 'image';
		};
		title?: string;
		body?: BlockContent;
	};
	contactData?: {
		name?: string;
		phone?: string;
		email?: string;
		contactHours?: string;
	};
	socialMedia?: {
		facebook?: string;
		instagram?: string;
		linkedin?: string;
	};
};

export type SiteSettings = {
	_id: string;
	_type: 'siteSettings';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	siteName?: string;
	siteDescription?: string;
	seo?: {
		title?: string;
		description?: string;
		ogImage?: {
			asset?: {
				_ref: string;
				_type: 'reference';
				_weak?: boolean;
				[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
			};
			media?: unknown;
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			alt?: string;
			caption?: string;
			_type: 'image';
		};
	};
};

export type Post = {
	_id: string;
	_type: 'post';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	excerpt?: string;
	price?: number;
	location?: {
		street?: string;
		number?: string;
		postalCode?: string;
		city?: string;
		country?: string;
	};
	features?: {
		bedrooms?: number;
		bathrooms?: number;
		garage?: number;
		livableArea?: number;
		landArea?: number;
	};
	contentImage?: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt?: string;
		caption?: string;
		_type: 'image';
	};
	imageGallery?: Array<{
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
		};
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		alt?: string;
		caption?: string;
		_type: 'contentImage';
		_key: string;
	}>;
	floorplan?: {
		asset?: {
			_ref: string;
			_type: 'reference';
			_weak?: boolean;
			[internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
		};
		media?: unknown;
		_type: 'file';
	};
	body?: BlockContent;
	ordering?: number;
	seo?: {
		title?: string;
		description?: string;
		ogImage?: {
			asset?: {
				_ref: string;
				_type: 'reference';
				_weak?: boolean;
				[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
			};
			media?: unknown;
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			alt?: string;
			caption?: string;
			_type: 'image';
		};
	};
};

export type Slug = {
	_type: 'slug';
	current?: string;
	source?: string;
};

export type SanityImagePaletteSwatch = {
	_type: 'sanity.imagePaletteSwatch';
	background?: string;
	foreground?: string;
	population?: number;
	title?: string;
};

export type SanityImagePalette = {
	_type: 'sanity.imagePalette';
	darkMuted?: SanityImagePaletteSwatch;
	lightVibrant?: SanityImagePaletteSwatch;
	darkVibrant?: SanityImagePaletteSwatch;
	vibrant?: SanityImagePaletteSwatch;
	dominant?: SanityImagePaletteSwatch;
	lightMuted?: SanityImagePaletteSwatch;
	muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
	_type: 'sanity.imageDimensions';
	height?: number;
	width?: number;
	aspectRatio?: number;
};

export type SanityImageMetadata = {
	_type: 'sanity.imageMetadata';
	location?: Geopoint;
	dimensions?: SanityImageDimensions;
	palette?: SanityImagePalette;
	lqip?: string;
	blurHash?: string;
	hasAlpha?: boolean;
	isOpaque?: boolean;
};

export type SanityFileAsset = {
	_id: string;
	_type: 'sanity.fileAsset';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash?: string;
	extension?: string;
	mimeType?: string;
	size?: number;
	assetId?: string;
	uploadId?: string;
	path?: string;
	url?: string;
	source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
	_type: 'sanity.assetSourceData';
	name?: string;
	id?: string;
	url?: string;
};

export type SanityImageAsset = {
	_id: string;
	_type: 'sanity.imageAsset';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash?: string;
	extension?: string;
	mimeType?: string;
	size?: number;
	assetId?: string;
	uploadId?: string;
	path?: string;
	url?: string;
	metadata?: SanityImageMetadata;
	source?: SanityAssetSourceData;
};

export type Geopoint = {
	_type: 'geopoint';
	lat?: number;
	lng?: number;
	alt?: number;
};

export type AllSanitySchemaTypes =
	| ContentImage
	| SanityImageCrop
	| SanityImageHotspot
	| BlockContent
	| PageContent
	| SiteSettings
	| Post
	| Slug
	| SanityImagePaletteSwatch
	| SanityImagePalette
	| SanityImageDimensions
	| SanityImageMetadata
	| SanityFileAsset
	| SanityAssetSourceData
	| SanityImageAsset
	| Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ../astro-app/src/sanity/queries/pageContent.ts
// Variable: PAGE_CONTENT_QUERY
// Query: *[_type == "pageContent"][0] {        id,        _createdAt,        publishedAt,        socialMedia,        newsletter{              title,  body,  contentImage {      asset->{    _id,    url,    metadata {      lqip,      dimensions { width, height, aspectRatio }    }  },  alt,  caption,  hotspot,  crop  }        },        region{              title,  body,  contentImage {      asset->{    _id,    url,    metadata {      lqip,      dimensions { width, height, aspectRatio }    }  },  alt,  caption,  hotspot,  crop  }        },        contactData    }
export type PAGE_CONTENT_QUERYResult = {
	id: null;
	_createdAt: string;
	publishedAt: null;
	socialMedia: {
		facebook?: string;
		instagram?: string;
		linkedin?: string;
	} | null;
	newsletter: {
		title: string | null;
		body: BlockContent | null;
		contentImage: {
			asset: {
				_id: string;
				url: string | null;
				metadata: {
					lqip: string | null;
					dimensions: {
						width: number | null;
						height: number | null;
						aspectRatio: number | null;
					} | null;
				} | null;
			} | null;
			alt: string | null;
			caption: string | null;
			hotspot: SanityImageHotspot | null;
			crop: SanityImageCrop | null;
		} | null;
	} | null;
	region: {
		title: string | null;
		body: BlockContent | null;
		contentImage: {
			asset: {
				_id: string;
				url: string | null;
				metadata: {
					lqip: string | null;
					dimensions: {
						width: number | null;
						height: number | null;
						aspectRatio: number | null;
					} | null;
				} | null;
			} | null;
			alt: string | null;
			caption: string | null;
			hotspot: SanityImageHotspot | null;
			crop: SanityImageCrop | null;
		} | null;
	} | null;
	contactData: {
		name?: string;
		phone?: string;
		email?: string;
		contactHours?: string;
	} | null;
} | null;
// Variable: PAGE_CONTENT_SOCIALS_QUERY
// Query: *[_type == "pageContent"][0] {        id,        _createdAt,        publishedAt,        socialMedia,    }
export type PAGE_CONTENT_SOCIALS_QUERYResult = {
	id: null;
	_createdAt: string;
	publishedAt: null;
	socialMedia: {
		facebook?: string;
		instagram?: string;
		linkedin?: string;
	} | null;
} | null;
// Variable: PAGE_CONTENT_NEWSLETTER_QUERY
// Query: *[_type == "pageContent"][0] {        id,        _createdAt,        publishedAt,        newsletter{              title,  body,  contentImage {      asset->{    _id,    url,    metadata {      lqip,      dimensions { width, height, aspectRatio }    }  },  alt,  caption,  hotspot,  crop  }        },    }
export type PAGE_CONTENT_NEWSLETTER_QUERYResult = {
	id: null;
	_createdAt: string;
	publishedAt: null;
	newsletter: {
		title: string | null;
		body: BlockContent | null;
		contentImage: {
			asset: {
				_id: string;
				url: string | null;
				metadata: {
					lqip: string | null;
					dimensions: {
						width: number | null;
						height: number | null;
						aspectRatio: number | null;
					} | null;
				} | null;
			} | null;
			alt: string | null;
			caption: string | null;
			hotspot: SanityImageHotspot | null;
			crop: SanityImageCrop | null;
		} | null;
	} | null;
} | null;
// Variable: PAGE_CONTENT_REGION_QUERY
// Query: *[_type == "pageContent"][0] {        id,        _createdAt,        publishedAt,        region{              title,  body,  contentImage {      asset->{    _id,    url,    metadata {      lqip,      dimensions { width, height, aspectRatio }    }  },  alt,  caption,  hotspot,  crop  }        },    }
export type PAGE_CONTENT_REGION_QUERYResult = {
	id: null;
	_createdAt: string;
	publishedAt: null;
	region: {
		title: string | null;
		body: BlockContent | null;
		contentImage: {
			asset: {
				_id: string;
				url: string | null;
				metadata: {
					lqip: string | null;
					dimensions: {
						width: number | null;
						height: number | null;
						aspectRatio: number | null;
					} | null;
				} | null;
			} | null;
			alt: string | null;
			caption: string | null;
			hotspot: SanityImageHotspot | null;
			crop: SanityImageCrop | null;
		} | null;
	} | null;
} | null;
// Variable: PAGE_CONTENT_CONTACT_QUERY
// Query: *[_type == "pageContent"][0] {        id,        _createdAt,        publishedAt,        contactData    }
export type PAGE_CONTENT_CONTACT_QUERYResult = {
	id: null;
	_createdAt: string;
	publishedAt: null;
	contactData: {
		name?: string;
		phone?: string;
		email?: string;
		contactHours?: string;
	} | null;
} | null;

// Source: ../astro-app/src/sanity/queries/posts.ts
// Variable: POSTS_SUMMARY_QUERY
// Query: *[_type == "post" && defined(slug.current)]  |  order(ordering asc, publishedAt) {    _id,    _createdAt,    publishedAt,    title,    slug,    price,    location {      street,      number,      postalCode,      city,      country    },    features {      bedrooms,      bathrooms,      landArea    },    contentImage {        asset->{    _id,    url,    metadata {      lqip,      dimensions { width, height, aspectRatio }    }  },  alt,  caption,  hotspot,  crop    },    seo  }
export type POSTS_SUMMARY_QUERYResult = Array<{
	_id: string;
	_createdAt: string;
	publishedAt: null;
	title: string | null;
	slug: Slug | null;
	price: number | null;
	location: {
		street: string | null;
		number: string | null;
		postalCode: string | null;
		city: string | null;
		country: string | null;
	} | null;
	features: {
		bedrooms: number | null;
		bathrooms: number | null;
		landArea: number | null;
	} | null;
	contentImage: {
		asset: {
			_id: string;
			url: string | null;
			metadata: {
				lqip: string | null;
				dimensions: {
					width: number | null;
					height: number | null;
					aspectRatio: number | null;
				} | null;
			} | null;
		} | null;
		alt: string | null;
		caption: string | null;
		hotspot: SanityImageHotspot | null;
		crop: SanityImageCrop | null;
	} | null;
	seo: {
		title?: string;
		description?: string;
		ogImage?: {
			asset?: {
				_ref: string;
				_type: 'reference';
				_weak?: boolean;
				[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
			};
			media?: unknown;
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			alt?: string;
			caption?: string;
			_type: 'image';
		};
	} | null;
}>;
// Variable: POST_BY_SLUG_QUERY
// Query: *[_type == "post" && slug.current == $slug][0] {    _id,    _createdAt,    publishedAt,    title,    slug,    price,    location {      street,      number,      postalCode,      city,      country    },    features {      bedrooms,      bathrooms,      garage,      livableArea,      landArea    },    contentImage {        asset->{    _id,    url,    metadata {      lqip,      dimensions { width, height, aspectRatio }    }  },  alt,  caption,  hotspot,  crop    },    "imageGallery": imageGallery[]{        asset->{    _id,    url,    metadata {      lqip,      dimensions { width, height, aspectRatio }    }  },  alt,  caption,  hotspot,  crop    },    "floorplan": floorplan.asset->,    "category": *[_id == ^.category._ref][0]{      _id,      title,      "slug": slug.current    },    body,    seo  }
export type POST_BY_SLUG_QUERYResult = {
	_id: string;
	_createdAt: string;
	publishedAt: null;
	title: string | null;
	slug: Slug | null;
	price: number | null;
	location: {
		street: string | null;
		number: string | null;
		postalCode: string | null;
		city: string | null;
		country: string | null;
	} | null;
	features: {
		bedrooms: number | null;
		bathrooms: number | null;
		garage: number | null;
		livableArea: number | null;
		landArea: number | null;
	} | null;
	contentImage: {
		asset: {
			_id: string;
			url: string | null;
			metadata: {
				lqip: string | null;
				dimensions: {
					width: number | null;
					height: number | null;
					aspectRatio: number | null;
				} | null;
			} | null;
		} | null;
		alt: string | null;
		caption: string | null;
		hotspot: SanityImageHotspot | null;
		crop: SanityImageCrop | null;
	} | null;
	imageGallery: Array<{
		asset: {
			_id: string;
			url: string | null;
			metadata: {
				lqip: string | null;
				dimensions: {
					width: number | null;
					height: number | null;
					aspectRatio: number | null;
				} | null;
			} | null;
		} | null;
		alt: string | null;
		caption: string | null;
		hotspot: SanityImageHotspot | null;
		crop: SanityImageCrop | null;
	}> | null;
	floorplan: {
		_id: string;
		_type: 'sanity.fileAsset';
		_createdAt: string;
		_updatedAt: string;
		_rev: string;
		originalFilename?: string;
		label?: string;
		title?: string;
		description?: string;
		altText?: string;
		sha1hash?: string;
		extension?: string;
		mimeType?: string;
		size?: number;
		assetId?: string;
		uploadId?: string;
		path?: string;
		url?: string;
		source?: SanityAssetSourceData;
	} | null;
	category: null;
	body: BlockContent | null;
	seo: {
		title?: string;
		description?: string;
		ogImage?: {
			asset?: {
				_ref: string;
				_type: 'reference';
				_weak?: boolean;
				[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
			};
			media?: unknown;
			hotspot?: SanityImageHotspot;
			crop?: SanityImageCrop;
			alt?: string;
			caption?: string;
			_type: 'image';
		};
	} | null;
} | null;
// Variable: POST_SLUGS_QUERY
// Query: *[_type == "post" && defined(slug.current)]{ "slug": slug.current }
export type POST_SLUGS_QUERYResult = Array<{
	slug: string | null;
}>;

// Source: ../astro-app/src/sanity/queries/siteSettings.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0] {        siteName,         siteDescription,        seo{                title,    description,    ogImage{          asset->{    _id,    url,    metadata {      lqip,      dimensions { width, height, aspectRatio }    }  },  alt,  caption,  hotspot,  crop    },        },    }
export type SITE_SETTINGS_QUERYResult = {
	siteName: string | null;
	siteDescription: string | null;
	seo: {
		title: string | null;
		description: string | null;
		ogImage: {
			asset: {
				_id: string;
				url: string | null;
				metadata: {
					lqip: string | null;
					dimensions: {
						width: number | null;
						height: number | null;
						aspectRatio: number | null;
					} | null;
				} | null;
			} | null;
			alt: string | null;
			caption: string | null;
			hotspot: SanityImageHotspot | null;
			crop: SanityImageCrop | null;
		} | null;
	} | null;
} | null;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
	interface SanityQueries {
		'\n        *[_type == "pageContent"][0] {\n        id,\n        _createdAt,\n        publishedAt,\n        socialMedia,\n        newsletter{\n            \n  title,\n  body,\n  contentImage {\n    \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions { width, height, aspectRatio }\n    }\n  },\n  alt,\n  caption,\n  hotspot,\n  crop\n\n  }\n\n        },\n        region{\n            \n  title,\n  body,\n  contentImage {\n    \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions { width, height, aspectRatio }\n    }\n  },\n  alt,\n  caption,\n  hotspot,\n  crop\n\n  }\n\n        },\n        contactData\n    }\n': PAGE_CONTENT_QUERYResult;
		'\n        *[_type == "pageContent"][0] {\n        id,\n        _createdAt,\n        publishedAt,\n        socialMedia,\n    }\n': PAGE_CONTENT_SOCIALS_QUERYResult;
		'\n        *[_type == "pageContent"][0] {\n        id,\n        _createdAt,\n        publishedAt,\n        newsletter{\n            \n  title,\n  body,\n  contentImage {\n    \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions { width, height, aspectRatio }\n    }\n  },\n  alt,\n  caption,\n  hotspot,\n  crop\n\n  }\n\n        },\n    }\n': PAGE_CONTENT_NEWSLETTER_QUERYResult;
		'\n        *[_type == "pageContent"][0] {\n        id,\n        _createdAt,\n        publishedAt,\n        region{\n            \n  title,\n  body,\n  contentImage {\n    \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions { width, height, aspectRatio }\n    }\n  },\n  alt,\n  caption,\n  hotspot,\n  crop\n\n  }\n\n        },\n    }\n': PAGE_CONTENT_REGION_QUERYResult;
		'\n        *[_type == "pageContent"][0] {\n        id,\n        _createdAt,\n        publishedAt,\n        contactData\n    }\n': PAGE_CONTENT_CONTACT_QUERYResult;
		'\n  *[_type == "post" && defined(slug.current)]\n  |  order(ordering asc, publishedAt) {\n    _id,\n    _createdAt,\n    publishedAt,\n    title,\n    slug,\n    price,\n    location {\n      street,\n      number,\n      postalCode,\n      city,\n      country\n    },\n    features {\n      bedrooms,\n      bathrooms,\n      landArea\n    },\n    contentImage {\n      \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions { width, height, aspectRatio }\n    }\n  },\n  alt,\n  caption,\n  hotspot,\n  crop\n\n    },\n    seo\n  }\n': POSTS_SUMMARY_QUERYResult;
		'\n  *[_type == "post" && slug.current == $slug][0] {\n    _id,\n    _createdAt,\n    publishedAt,\n    title,\n    slug,\n    price,\n    location {\n      street,\n      number,\n      postalCode,\n      city,\n      country\n    },\n    features {\n      bedrooms,\n      bathrooms,\n      garage,\n      livableArea,\n      landArea\n    },\n    contentImage {\n      \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions { width, height, aspectRatio }\n    }\n  },\n  alt,\n  caption,\n  hotspot,\n  crop\n\n    },\n    "imageGallery": imageGallery[]{\n      \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions { width, height, aspectRatio }\n    }\n  },\n  alt,\n  caption,\n  hotspot,\n  crop\n\n    },\n    "floorplan": floorplan.asset->,\n    "category": *[_id == ^.category._ref][0]{\n      _id,\n      title,\n      "slug": slug.current\n    },\n    body,\n    seo\n  }\n': POST_BY_SLUG_QUERYResult;
		'\n  *[_type == "post" && defined(slug.current)]{ "slug": slug.current }\n': POST_SLUGS_QUERYResult;
		'\n    *[_type == "siteSettings"][0] {\n        siteName, \n        siteDescription,\n        seo{\n            \n    title,\n    description,\n    ogImage{\n        \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions { width, height, aspectRatio }\n    }\n  },\n  alt,\n  caption,\n  hotspot,\n  crop\n\n    },\n\n        },\n    }\n': SITE_SETTINGS_QUERYResult;
	}
}
